import type { CSSProperties } from "react";
import { colors, spacing, borderRadius, shadows } from "../theme";

export const chartStyles: { [key: string]: CSSProperties } = {
  section: {
    backgroundColor: colors.card,
    padding: spacing.lg,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.xl,
    boxShadow: shadows.sm,
    border: `1px solid ${colors.border}`,
  },
  sectionTitle: {
    color: colors.textPrimary,
    margin: `0 0 ${spacing.md} 0`,
    fontSize: "1.1rem",
    fontWeight: 600,
  },
  container: {
    height: "250px",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    marginTop: spacing.lg,
    padding: `${spacing.md} ${spacing.lg}`,
    backgroundColor: colors.background,
    borderRadius: borderRadius.md,
  },
  bars: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-around",
    width: "100%",
    height: "100%",
  },
  barContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    height: "100%",
    flex: 1,
    margin: `0 ${spacing.xs}`,
  },
  barLabel: {
    fontSize: "0.8rem",
    color: colors.textSecondary,
    marginBottom: spacing.xs,
    fontWeight: 500,
    textAlign: "center",
  },
  barWrapper: {
    height: "calc(100% - 40px)",
    width: "100%",
    maxWidth: "60px",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
  },
  bar: {
    width: "100%",
    maxWidth: "40px",
    transition: "height 0.3s ease",
    borderRadius: `${borderRadius.xs} ${borderRadius.xs} 0 0`,
    backgroundColor: colors.chartPrimary,
  },
  barHover: {
    opacity: 0.9,
    transform: "scale(1.05)",
  },
  barValue: {
    fontSize: "0.75rem",
    color: colors.textTertiary,
    marginTop: spacing.xs,
    textAlign: "center",
    fontWeight: 500,
  },
  tooltip: {
    position: "absolute",
    backgroundColor: colors.dark,
    color: colors.textOnDark,
    padding: `${spacing.xs} ${spacing.sm}`,
    borderRadius: borderRadius.xs,
    fontSize: "0.8rem",
    pointerEvents: "none",
    zIndex: 1000,
    boxShadow: shadows.md,
  },
};