import type { CSSProperties } from "react";
import { colors, spacing, borderRadius, shadows } from "../theme";

export const formStyles: { [key: string]: CSSProperties } = {
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.lg,
    paddingBottom: spacing.md,
    borderBottom: `1px solid ${colors.border}`,
  },
  addButton: {
    backgroundColor: colors.primary,
    color: colors.white,
    border: "none",
    padding: `${spacing.sm} ${spacing.lg}`,
    borderRadius: borderRadius.md,
    cursor: "pointer",
    fontSize: "0.9rem",
    fontWeight: 600,
    transition: "all 0.2s",
    boxShadow: shadows.sm,
  },
  addButtonHover: {
    backgroundColor: colors.primaryDark,
    transform: "translateY(-1px)",
    boxShadow: shadows.md,
  },
  form: {
    backgroundColor: colors.formBackground,
    padding: spacing.lg,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.xl,
    boxShadow: shadows.sm,
    border: `1px solid ${colors.border}`,
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: spacing.lg,
    marginBottom: spacing.lg,
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
  },
  label: {
    marginBottom: spacing.xs,
    color: colors.textPrimary,
    fontWeight: 500,
    fontSize: "0.9rem",
  },
  input: {
    padding: `${spacing.sm} ${spacing.md}`,
    border: `1px solid ${colors.formBorder}`,
    borderRadius: borderRadius.sm,
    fontSize: "0.9rem",
    color: colors.textPrimary,
    backgroundColor: colors.white,
    transition: "all 0.2s",
  },
  inputFocus: {
    borderColor: colors.formFocus,
    boxShadow: `0 0 0 3px ${colors.formFocus}20`,
    outline: "none",
  },
  textarea: {
    padding: spacing.sm,
    border: `1px solid ${colors.formBorder}`,
    borderRadius: borderRadius.sm,
    fontSize: "0.9rem",
    color: colors.textPrimary,
    backgroundColor: colors.white,
    resize: "vertical",
    minHeight: "80px",
    transition: "all 0.2s",
  },
  select: {
    padding: `${spacing.sm} ${spacing.md}`,
    border: `1px solid ${colors.formBorder}`,
    borderRadius: borderRadius.sm,
    fontSize: "0.9rem",
    color: colors.textPrimary,
    backgroundColor: colors.white,
    cursor: "pointer",
  },
  checkboxContainer: {
    display: "flex",
    alignItems: "center",
    gap: spacing.sm,
    cursor: "pointer",
  },
  checkbox: {
    width: "18px",
    height: "18px",
    cursor: "pointer",
  },
  formActions: {
    display: "flex",
    gap: spacing.md,
    justifyContent: "flex-end",
    paddingTop: spacing.md,
    borderTop: `1px solid ${colors.borderLight}`,
  },
  saveButton: {
    backgroundColor: colors.success,
    color: colors.white,
    border: "none",
    padding: `${spacing.sm} ${spacing.lg}`,
    borderRadius: borderRadius.md,
    cursor: "pointer",
    fontSize: "0.9rem",
    fontWeight: 600,
    transition: "all 0.2s",
    minWidth: "120px",
  },
  saveButtonHover: {
    backgroundColor: colors.successDark,
    transform: "translateY(-1px)",
    boxShadow: shadows.sm,
  },
  cancelButton: {
    backgroundColor: colors.gray,
    color: colors.white,
    border: "none",
    padding: `${spacing.sm} ${spacing.lg}`,
    borderRadius: borderRadius.md,
    cursor: "pointer",
    fontSize: "0.9rem",
    fontWeight: 600,
    transition: "all 0.2s",
    minWidth: "120px",
  },
  cancelButtonHover: {
    backgroundColor: colors.grayDark,
    transform: "translateY(-1px)",
  },
  smallButton: {
    padding: `${spacing.xs} ${spacing.sm}`,
    backgroundColor: colors.gray,
    color: colors.white,
    border: "none",
    borderRadius: borderRadius.sm,
    cursor: "pointer",
    fontSize: "0.8rem",
    fontWeight: 500,
    transition: "all 0.2s",
    marginRight: spacing.xs,
  },
  smallButtonHover: {
    backgroundColor: colors.grayDark,
  },
  editButton: {
    backgroundColor: colors.info,
  },
  editButtonHover: {
    backgroundColor: colors.infoDark,
  },
  deleteButton: {
    backgroundColor: colors.danger,
  },
  deleteButtonHover: {
    backgroundColor: colors.dangerDark,
  },
  errorMessage: {
    color: colors.danger,
    fontSize: "0.85rem",
    marginTop: spacing.xs,
    padding: spacing.xs,
    backgroundColor: `${colors.danger}10`,
    borderRadius: borderRadius.xs,
  },
};