import { CSSProperties } from "react";

const HistoryListPageStyles: { [key: string]: CSSProperties } = {
  container: {
    width: "100%",
    maxWidth: "600px",
    margin: "0 auto",
    backgroundColor: "#f5f7fa",
    minHeight: "100vh",
  },

  backButton: {
    background: "none",
    border: "none",
    fontSize: "1.5rem",
    color: "white",
    cursor: "pointer",
    marginRight: "10px",
    padding: "5px",
  },
  headerActions: {
    display: "flex",
    gap: "10px",
  },
  iconButton: {
    background: "rgba(255, 255, 255, 0.2)",
    border: "none",
    borderRadius: "50%",
    width: "40px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.2rem",
    color: "white",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  chartSection: {
    backgroundColor: "white",
    borderRadius: "12px",
    margin: "15px",
    padding: "16px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.08)",
    border: "1px solid #e9ecef",
  },
  chartWrapper: {
    position: "relative",
    height: "220px",
    width: "100%",
    marginTop: "8px",
  },
  emptyChart: {
    textAlign: "center" as const,
    padding: "20px",
    color: "#6c757d",
  },
  emptyChartIcon: {
    fontSize: "2rem",
    marginBottom: "8px",
    opacity: 0.5,
  },
  emptyChartText: {
    fontSize: "0.9rem",
    fontWeight: 500,
    marginBottom: "4px",
  },
  emptyChartSubtext: {
    fontSize: "0.8rem",
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "12px",
    padding: "16px 16px 0 16px",
  },
  sectionTitle: {
    fontSize: "1rem",
    fontWeight: 600,
    color: "#333",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  sectionIcon: {
    fontSize: "1.1rem",
  },
  sectionSubtitle: {
    fontSize: "0.8rem",
    color: "#666",
  },
  currentMonthCard: {
    backgroundColor: "white",
    borderRadius: "12px",
    margin: "15px",
    padding: "16px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.08)",
    border: "1px solid #e9ecef",
  },
  currentMonthHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "16px",
  },
  currentMonthIcon: {
    fontSize: "1.8rem",
    backgroundColor: "#e8f0fe",
    color: "#4285f4",
    width: "44px",
    height: "44px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  currentMonthTitle: {
    fontSize: "1rem",
    fontWeight: 600,
    color: "#333",
  },
  currentMonthDate: {
    fontSize: "0.85rem",
    color: "#666",
  },
  currentMonthValues: {
    backgroundColor: "#f8f9fa",
    borderRadius: "8px",
    padding: "12px",
  },
  currentMonthRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "6px 0",
    fontSize: "0.9rem",
  },
  currentMonthAmount: {
    fontWeight: 600,
    color: "#333",
  },
  currentMonthTotal: {
    borderTop: "1px solid #ddd",
    paddingTop: "8px",
    marginTop: "4px",
  },
  currentMonthTotalAmount: {
    fontWeight: 700,
    fontSize: "1rem",
    color: "#4285f4",
  },
  section: {
    backgroundColor: "white",
    borderRadius: "12px",
    margin: "15px",
    padding: "0",
    boxShadow: "0 2px 8px rgba(0,0,0,0.06)",
    border: "1px solid #e9ecef",
    overflow: "hidden",
  },
  tableContainer: {
    overflow: "hidden",
    borderRadius: "8px",
    border: "1px solid #e9ecef",
  },
  tableHeader: {
    display: "flex",
    padding: "10px 12px",
    backgroundColor: "#f8f9fa",
    borderBottom: "1px solid #e9ecef",
    fontSize: "0.8rem",
    fontWeight: 600,
    color: "#495057",
  },
  headerCell: {
    padding: "0 4px",
  },
  tableBody: {
    maxHeight: "400px",
    overflowY: "auto",
  },
  tableRow: {
    display: "flex",
    alignItems: "center",
    padding: "8px 12px",
    minHeight: "44px",
    borderBottom: "1px solid #f0f0f0",
  },
  editRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    width: "100%",
  },
  cell: {
    padding: "0 4px",
    display: "flex",
    alignItems: "center",
  },
  monthDisplay: {
    minWidth: "0",
  },
  monthName: {
    fontSize: "0.9rem",
    fontWeight: 600,
    color: "#333",
    lineHeight: 1.2,
  },
  monthId: {
    fontSize: "0.7rem",
    color: "#888",
    marginTop: "1px",
  },
  amountDisplay: {
    fontSize: "0.9rem",
    fontWeight: 600,
    color: "#333",
    lineHeight: 1.2,
  },
  savingsNote: {
    fontSize: "0.7rem",
    color: "#666",
    marginTop: "1px",
    fontStyle: "italic",
  },
  editInput: {
    padding: "6px 8px",
    border: "1px solid #ddd",
    borderRadius: "4px",
    fontSize: "0.85rem",
    width: "100%",
    boxSizing: "border-box" as const,
  },
  actionButtons: {
    display: "flex",
    gap: "6px",
  },
  editButton: {
    background: "none",
    border: "none",
    fontSize: "0.9rem",
    cursor: "pointer",
    opacity: 0.7,
    padding: "4px",
    borderRadius: "4px",
    minWidth: "28px",
    minHeight: "28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  deleteButton: {
    background: "none",
    border: "none",
    fontSize: "0.9rem",
    cursor: "pointer",
    opacity: 0.7,
    padding: "4px",
    borderRadius: "4px",
    minWidth: "28px",
    minHeight: "28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  saveButton: {
    background: "none",
    border: "none",
    fontSize: "1rem",
    color: "#34a853",
    cursor: "pointer",
    padding: "4px",
    borderRadius: "4px",
    minWidth: "28px",
    minHeight: "28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  cancelButton: {
    background: "none",
    border: "none",
    fontSize: "1rem",
    color: "#ea4335",
    cursor: "pointer",
    padding: "4px",
    borderRadius: "4px",
    minWidth: "28px",
    minHeight: "28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyState: {
    textAlign: "center" as const,
    padding: "30px 20px",
    color: "#6c757d",
  },
  emptyIcon: {
    fontSize: "2.5rem",
    marginBottom: "12px",
    opacity: 0.5,
  },
  emptyText: {
    fontSize: "0.95rem",
    fontWeight: 500,
    marginBottom: "4px",
  },
  emptySubtext: {
    fontSize: "0.8rem",
  },
  dialogOverlay: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  dialog: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "20px",
    width: "90%",
    maxWidth: "350px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.2)",
  },
  dialogTitle: {
    fontSize: "1.1rem",
    fontWeight: 600,
    color: "#333",
    marginBottom: "12px",
  },
  dialogMessage: {
    fontSize: "0.9rem",
    color: "#666",
    marginBottom: "20px",
    lineHeight: 1.4,
  },
  dialogButtons: {
    display: "flex",
    gap: "10px",
  },
  dialogCancel: {
    flex: 1,
    padding: "10px",
    border: "1px solid #ddd",
    borderRadius: "6px",
    backgroundColor: "white",
    color: "#666",
    fontSize: "0.9rem",
    fontWeight: 500,
    cursor: "pointer",
  },
  dialogConfirm: {
    flex: 1,
    padding: "10px",
    border: "none",
    borderRadius: "6px",
    backgroundColor: "#ea4335",
    color: "white",
    fontSize: "0.9rem",
    fontWeight: 500,
    cursor: "pointer",
  },
};

export default HistoryListPageStyles;