import { CSSProperties } from "react";

const styles: { [key: string]: CSSProperties } = {
  container: {
    width: "100%",
    maxWidth: "500px",
    margin: "0 auto",
    backgroundColor: "#f5f7fa",
    minHeight: "100vh",
  },
  backButton: {
    background: "none",
    border: "none",
    fontSize: "1.5rem",
    color: "white",
    cursor: "pointer",
    marginRight: "10px",
    padding: "5px",
  },
  content: {
    padding: "15px",
  },
  toggleContainer: {
    backgroundColor: "white",
    borderRadius: "8px",
    padding: "12px 15px",
    marginBottom: "15px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
    border: "1px solid #e9ecef",
  },
  toggleLabel: {
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
  },
  toggleInput: {
    marginRight: "10px",
    width: "18px",
    height: "18px",
  },
  toggleText: {
    fontSize: "0.9rem",
    color: "#666",
  },
  errorContainer: {
    backgroundColor: "#feebee",
    border: "1px solid #f44336",
    borderRadius: "8px",
    padding: "12px 15px",
    marginBottom: "15px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  errorIcon: {
    fontSize: "1.2rem",
    color: "#f44336",
  },
  errorText: {
    flex: 1,
    fontSize: "0.9rem",
    color: "#d32f2f",
  },
  errorClose: {
    background: "none",
    border: "none",
    fontSize: "1rem",
    color: "#666",
    cursor: "pointer",
    padding: "2px 6px",
    borderRadius: "4px",
  },
  tableContainer: {
    backgroundColor: "white",
    borderRadius: "12px",
    overflow: "hidden",
    marginBottom: "15px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.08)",
    border: "1px solid #e9ecef",
  },
  tableHeader: {
    display: "flex",
    backgroundColor: "#f8f9fa",
    padding: "15px",
    borderBottom: "2px solid #e9ecef",
    fontSize: "0.9rem",
    fontWeight: 600,
    color: "#495057",
  },
  headerCell: {
    padding: "0 8px",
  },
  tableBody: {
    maxHeight: "400px",
    overflowY: "auto",
  },
  tableRow: {
    display: "flex",
    alignItems: "center",
    padding: "12px 15px",
    borderBottom: "1px solid #f0f0f0",
    minHeight: "60px",
  },
  cell: {
    padding: "0 8px",
    display: "flex",
    alignItems: "center",
  },
  accountCode: {
    fontSize: "0.95rem",
    fontWeight: 500,
    color: "#333",
  },
  amountDisplay: {
    fontSize: "0.95rem",
    color: "#333",
    fontWeight: 500,
  },
  editInputContainer: {
    position: "relative",
    width: "100%",
  },
  editInput: {
    width: "100%",
    padding: "8px 24px 8px 8px",
    border: "1px solid #ddd",
    borderRadius: "6px",
    fontSize: "0.9rem",
    textAlign: "right",
  },
  lakhSuffix: {
    position: "absolute",
    right: "8px",
    top: "50%",
    transform: "translateY(-50%)",
    color: "#666",
    fontSize: "0.8rem",
  },
  actionButtons: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
  },
  saveButton: {
    background: "#34a853",
    border: "none",
    fontSize: "0.9rem",
    color: "white",
    cursor: "pointer",
    padding: "6px 10px",
    borderRadius: "4px",
    minWidth: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
  },
  cancelButton: {
    background: "#ea4335",
    border: "none",
    fontSize: "0.9rem",
    color: "white",
    cursor: "pointer",
    padding: "6px 10px",
    borderRadius: "4px",
    minWidth: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
  },
  editButton: {
    background: "none",
    border: "1px solid #ddd",
    fontSize: "0.9rem",
    color: "#666",
    cursor: "pointer",
    padding: "6px 10px",
    borderRadius: "4px",
    minWidth: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  spinnerSmall: {
    width: "12px",
    height: "12px",
    border: "2px solid rgba(255,255,255,0.3)",
    borderTopColor: "white",
    borderRadius: "50%",
  },
  totalsRow: {
    display: "flex",
    alignItems: "center",
    padding: "15px",
    backgroundColor: "#f8f9fa",
    borderTop: "2px solid #e9ecef",
    fontSize: "0.95rem",
  },
  totalsCell: {
    padding: "0 8px",
  },
  totalChangeIndicator: {
    fontSize: "0.7rem",
    color: "#666",
    fontStyle: "italic",
  },
  instructions: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "15px",
    marginBottom: "15px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.08)",
    border: "1px solid #e9ecef",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  instructionItem: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "0.85rem",
    color: "#666",
  },
  instructionIcon: {
    fontSize: "1rem",
    width: "24px",
    textAlign: "center" as const,
  },
  firebaseInfo: {
    backgroundColor: "#e8f0fe",
    borderRadius: "12px",
    padding: "15px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.08)",
    border: "1px solid #bbdefb",
    fontSize: "0.8rem",
  },
  infoTitle: {
    fontWeight: "bold",
    marginBottom: "8px",
    color: "#1976d2",
  },
  infoRow: {
    display: "flex",
    marginBottom: "4px",
  },
  infoLabel: {
    fontWeight: "500",
    width: "100px",
    color: "#0d47a1",
  },
  infoValue: {
    flex: 1,
    color: "#424242",
  },
  emptyState: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "40px 20px",
    textAlign: "center" as const,
    boxShadow: "0 2px 8px rgba(0,0,0,0.08)",
    border: "1px solid #e9ecef",
    marginTop: "20px",
  },
  emptyIcon: {
    fontSize: "3rem",
    marginBottom: "15px",
    opacity: 0.5,
  },
  emptyText: {
    fontSize: "1.1rem",
    fontWeight: 500,
    marginBottom: "5px",
    color: "#333",
  },
  emptySubtext: {
    fontSize: "0.9rem",
    color: "#666",
    marginBottom: "20px",
  },
  addButton: {
    padding: "12px 24px",
    border: "none",
    borderRadius: "8px",
    backgroundColor: "#4285f4",
    color: "white",
    fontSize: "0.95rem",
    fontWeight: 500,
    cursor: "pointer",
  },
};

export default styles;